#!/usr/bin/env python3
DNAseq=input("Enter DNA sequence: ")

complement=DNAseq[::-1]

comp_table=str.maketrans({'T':'A', 'A':'T', 'G':'C', 'C':'G'})

revcomp=complement.translate(comp_table)

print(revcomp)


